version: "3.9"

services:
  db:
    platform: linux/amd64
    image: mysql:8.0
    container_name: mysql_db_v2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: web_search_development
      MYSQL_USER: web_search
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build:
      context: .
    container_name: rails_app
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "4000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql2://web_search:password@db:3306/web_search_development

volumes:
  db_data:
