swagger: "2.0"
info:
  title: Sample API
  description: API documentation for Sample App
  version: "1.0.0"
host: localhost:4000
schemes:
  - http
paths:
  /examples:
    get:
      summary: Retrieve a list of examples
      responses:
        '200':
          description: successful operation
