default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: web_search
  password: password
  host: db

development:
  <<: *default
  database: web_search_development

test:
  <<: *default
  database: web_search_test

production:
  <<: *default
  database: web_search_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
